version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r app/requirements.txt

      - run:
          name: Test app
          command: |
            python app/app.py &
            sleep 5

      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install -y ansible

      - run:
          name: Run Ansible Playbook
          command: |
            ansible-playbook ansible/playbook.yml -i ansible/inventory.ini

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
